permalink: "/:year/:month/:day/:title/"
markdown: kramdown
relative_permalinks: false
exclude:
  - 'Guardfile'
  - 'Gemfile*'
  - '.gitignore'
  - 'Rakefile'
  - 'README.markdown'
  - 'vendor'

prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published?"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
